/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2022-01-08 07:21:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\" style=\"background-color: #00BFFF;\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div style=\"color: #1E90FF; text-align: center;\">Register</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("						<form class=\"form-horizontal\" method=\"post\" action=\"#\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"name\" class=\"cols-sm-2 control-label\">Your\r\n");
      out.write("									Name</label>\r\n");
      out.write("								<div class=\"cols-sm-10\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<span class=\"input-group-addon\"><i\r\n");
      out.write("											class=\"fa fa-user fa\" aria-hidden=\"true\"></i></span> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"name\" id=\"name\"\r\n");
      out.write("											placeholder=\"Enter your Name\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"email\" class=\"cols-sm-2 control-label\">Your\r\n");
      out.write("									Email</label>\r\n");
      out.write("								<div class=\"cols-sm-10\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<span class=\"input-group-addon\"><i\r\n");
      out.write("											class=\"fa fa-envelope fa\" aria-hidden=\"true\"></i></span> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"email\" id=\"email\"\r\n");
      out.write("											placeholder=\"Enter your Email\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"username\" class=\"cols-sm-2 control-label\">Username</label>\r\n");
      out.write("								<div class=\"cols-sm-10\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<span class=\"input-group-addon\"><i\r\n");
      out.write("											class=\"fa fa-users fa\" aria-hidden=\"true\"></i></span> <input\r\n");
      out.write("											type=\"text\" class=\"form-control\" name=\"username\"\r\n");
      out.write("											id=\"username\" placeholder=\"Enter your Username\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"password\" class=\"cols-sm-2 control-label\">Password</label>\r\n");
      out.write("								<div class=\"cols-sm-10\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<span class=\"input-group-addon\"><i\r\n");
      out.write("											class=\"fa fa-lock fa-lg\" aria-hidden=\"true\"></i></span> <input\r\n");
      out.write("											type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("											id=\"password\" placeholder=\"Enter your Password\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"confirm\" class=\"cols-sm-2 control-label\">Confirm\r\n");
      out.write("									Password</label>\r\n");
      out.write("								<div class=\"cols-sm-10\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<span class=\"input-group-addon\"><i\r\n");
      out.write("											class=\"fa fa-lock fa-lg\" aria-hidden=\"true\"></i></span> <input\r\n");
      out.write("											type=\"password\" class=\"form-control\" name=\"confirm\"\r\n");
      out.write("											id=\"confirm\" placeholder=\"Confirm your Password\" />\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group \">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"btn btn-primary btn-lg btn-block login-button\">Register</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"login-register\">\r\n");
      out.write("								<a href=\"Layer.jsp\">Login</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
