/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2022-01-07 07:28:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class doi2doicapdat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Mukta');\r\n");
      out.write("body{\r\n");
      out.write("  font-family: 'Mukta', sans-serif;\r\n");
      out.write("	height:100vh;\r\n");
      out.write("	min-height:550px;\r\n");
      out.write("	background-image: url(http://www.planwallpaper.com/static/images/Free-Wallpaper-Nature-Scenes.jpg);\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size:cover;\r\n");
      out.write("	background-position:center;\r\n");
      out.write("	position:relative;\r\n");
      out.write("    overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  color:#444444;\r\n");
      out.write("}\r\n");
      out.write(".login-reg-panel{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("	text-align:center;\r\n");
      out.write("    width:70%;\r\n");
      out.write("	right:0;left:0;\r\n");
      out.write("    margin:auto;\r\n");
      out.write("    height:400px;\r\n");
      out.write("    background-color: rgba(236, 48, 20, 0.9);\r\n");
      out.write("}\r\n");
      out.write(".white-panel{\r\n");
      out.write("    background-color: rgba(255,255, 255, 1);\r\n");
      out.write("    height:500px;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:-50px;\r\n");
      out.write("    width:50%;\r\n");
      out.write("    right:calc(50% - 50px);\r\n");
      out.write("    transition:.3s ease-in-out;\r\n");
      out.write("    z-index:0;\r\n");
      out.write("    box-shadow: 0 0 15px 9px #00000096;\r\n");
      out.write("}\r\n");
      out.write(".login-reg-panel input[type=\"radio\"]{\r\n");
      out.write("    position:relative;\r\n");
      out.write("    display:none;\r\n");
      out.write("}\r\n");
      out.write(".login-reg-panel{\r\n");
      out.write("    color:#B8B8B8;\r\n");
      out.write("}\r\n");
      out.write(".login-reg-panel #label-login, \r\n");
      out.write(".login-reg-panel #label-register{\r\n");
      out.write("    border:1px solid #9E9E9E;\r\n");
      out.write("    padding:5px 5px;\r\n");
      out.write("    width:150px;\r\n");
      out.write("    display:block;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write(".login-info-box{\r\n");
      out.write("    width:30%;\r\n");
      out.write("    padding:0 50px;\r\n");
      out.write("    top:20%;\r\n");
      out.write("    left:0;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    text-align:left;\r\n");
      out.write("}\r\n");
      out.write(".register-info-box{\r\n");
      out.write("    width:30%;\r\n");
      out.write("    padding:0 50px;\r\n");
      out.write("    top:20%;\r\n");
      out.write("    right:0;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    text-align:left;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".right-log{right:50px !important;}\r\n");
      out.write("\r\n");
      out.write(".login-show, \r\n");
      out.write(".register-show{\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    display:none;\r\n");
      out.write("    opacity:0;\r\n");
      out.write("    transition:0.3s ease-in-out;\r\n");
      out.write("    color:#242424;\r\n");
      out.write("    text-align:left;\r\n");
      out.write("    padding:50px;\r\n");
      out.write("}\r\n");
      out.write(".show-log-panel{\r\n");
      out.write("    display:block;\r\n");
      out.write("    opacity:0.9;\r\n");
      out.write("}\r\n");
      out.write(".login-show input[type=\"text\"], .login-show input[type=\"password\"]{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin:20px 0;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    border: 1px solid #b5b5b5;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".login-show input[type=\"button\"] {\r\n");
      out.write("    max-width: 150px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: #444444;\r\n");
      out.write("    color: #f9f9f9;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("    float:right;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".login-show a{\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    padding:10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register-show input[type=\"text\"], .register-show input[type=\"password\"]{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin:20px 0;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    border: 1px solid #b5b5b5;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".register-show input[type=\"button\"] {\r\n");
      out.write("    max-width: 150px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: #444444;\r\n");
      out.write("    color: #f9f9f9;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    border-radius: 2px;\r\n");
      out.write("    float:right;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".credit {\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    bottom:10px;\r\n");
      out.write("    left:10px;\r\n");
      out.write("    color: #3B3B25;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-family: Arial,sans-serif;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  color:#2c7715;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"login-reg-panel\">\r\n");
      out.write("		<div class=\"login-info-box\">\r\n");
      out.write("			<h2>Have an account?</h2>\r\n");
      out.write("			<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("			<label id=\"label-register\" for=\"log-reg-show\">Login</label>\r\n");
      out.write("			<input type=\"radio\" name=\"active-log-panel\" id=\"log-reg-show\"  checked=\"checked\">\r\n");
      out.write("		</div>\r\n");
      out.write("							\r\n");
      out.write("		<div class=\"register-info-box\">\r\n");
      out.write("			<h2>Don't have an account?</h2>\r\n");
      out.write("			<p>Lorem ipsum dolor sit amet</p>\r\n");
      out.write("			<label id=\"label-login\" for=\"log-login-show\">Register</label>\r\n");
      out.write("			<input type=\"radio\" name=\"active-log-panel\" id=\"log-login-show\">\r\n");
      out.write("		</div>\r\n");
      out.write("							\r\n");
      out.write("		<div class=\"white-panel\">\r\n");
      out.write("			<div class=\"login-show\">\r\n");
      out.write("				<h2>LOGIN</h2>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"Password\">\r\n");
      out.write("				<input type=\"button\" value=\"Login\">\r\n");
      out.write("				<a href=\"\">Forgot password?</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"register-show\">\r\n");
      out.write("				<h2>REGISTER</h2>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"Password\">\r\n");
      out.write("				<input type=\"password\" placeholder=\"Confirm Password\">\r\n");
      out.write("				<input type=\"button\" value=\"Register\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
