/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.10
 * Generated at: 2022-01-10 00:09:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel='stylesheet'\r\n");
      out.write("	href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	font-family: arial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	background-color: #4FD9A7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header span, .mid .left span {\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mid .title, .search {\r\n");
      out.write("	background-color: #4FD9A7;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mid p {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span:hover, .mid span:hover {\r\n");
      out.write("	color: #4FD9A7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right span {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mid .genre {\r\n");
      out.write("	background: black;\r\n");
      out.write("	color: white;\r\n");
      out.write("	display: inline;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"top\">\r\n");
      out.write("				<div class=\"row mt-1 py-1 navbar navbar-expand-md\">\r\n");
      out.write("					<div class=\"logo col-md-2 col-sm-2 col-3\">\r\n");
      out.write("						<img class=\"navbar-brand\" height=\"40\"\r\n");
      out.write("							src=\"img/z3084541674816_e8384d2f3c44b472e9e4645a9b99f01e.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<form class=\"d-flex col-md-8 col-sm-7 col-6\" action=\"\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Nhập nội dung cần tìm kiếm\">\r\n");
      out.write("							<div class=\"input-group-append\">\r\n");
      out.write("								<button class=\"btn btn-secondary\" type=\"button\">\r\n");
      out.write("									<i class=\"fa fa-search\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<a class=\"navbar nav-link col-md-2 col-sm-3 col-3\"\r\n");
      out.write("						href=\"https://www.google.com.vn/?hl=vi\"><span class=\"ms-auto \" style=\"color: black;\">\r\n");
      out.write("							 <iclass=\"fas fa-user\"></i> Đăng Xuất</span></a>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<nav class=\"mt-1 py-1 navbar navbar-dark navbar-expand-md \">\r\n");
      out.write("					<button data-bs-toggle=\"collapse\" data-bs-target=\"#main-menu\"\r\n");
      out.write("						type=\"button\" class=\"navbar-toggler\">\r\n");
      out.write("						<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<div class=\"collapse navbar-collapse\" id=\"main-menu\">\r\n");
      out.write("						<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"active nav-link\" href=\"\">Trang\r\n");
      out.write("									chủ</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"\">Điện\r\n");
      out.write("									ảnh - Truyền hình</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"\">Âm nhạc</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"\">Game</a></li>\r\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"\">Truyện\r\n");
      out.write("									tranh</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header mt-3 row\">\r\n");
      out.write("				<a\r\n");
      out.write("					href=\"https://saostar.vn/giai-tri/lynk-lee-chia-se-ve-ke-hoach-lap-gia-dinh-tiet-lo-bi-mat-tinh-cam-202112171646129862.html\"\r\n");
      out.write("					class=\"col-md-7 col-sm-7 col-12 nav-link\"> <img\r\n");
      out.write("					class=\"rounded img-fluid\" width=\"1100\" alt=\"\"\r\n");
      out.write("					src=\"img/lynk-1594449930-width800height583.jpg\"> <span\r\n");
      out.write("					style=\"font-size: 20px\"> Lynk Lee chia sẻ về kế hoạch lập\r\n");
      out.write("						gia đình, tiết lộ bí mật tình cảm</span>\r\n");
      out.write("				</a>\r\n");
      out.write("				<div class=\"col-md-5 col-sm-5 col-12\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("							class=\"col-md-12 col-sm-12 col-12 nav-link\"><img\r\n");
      out.write("							class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("							src=\"img/0257ef2019954d7f87c7b7d7bbe780b7-1635679097-93.jpeg\">\r\n");
      out.write("							<span>Trung Quốc cảnh báo game blockchain lừa đảo...</span> </a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row mt-1\">\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://game4v.com/anime-spy-x-family-tung-ra-trailer-moi-cung-nhung-thong-tin-bo-sung-ve-dan-dien-vien-long-tieng-825628.g4v\"\r\n");
      out.write("							class=\"col-md-6 col-sm-6 col-6 nav-link\"><img\r\n");
      out.write("							class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("							src=\"img/Spy-x-Family-trailer-1639792884-18.jpg\"> <span>Anime\r\n");
      out.write("								Spy x Family tung ra trailer mới cùng những thông tin ...</span> </a> <a\r\n");
      out.write("							href=\"https://saovietnews.com/2021/12/18/cuoc-song-cua-ong-bo-quoc-dan-trung-anh-sau-khi-ve-huu/\"\r\n");
      out.write("							class=\"col-md-6 col-sm-6 col-6 nav-link\"><img\r\n");
      out.write("							class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("							src=\"img/cuoc-song-cua-ong-bo-quoc-dan-trung-anh-sau-khi-ve-huu.jpg\">\r\n");
      out.write("							<span>Cuộc sống của “ông bố quốc dân” Trung Anh sau khi về\r\n");
      out.write("								hưu </span> </a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"mid mt-3\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-8 col-sm-8 col-12 left\">\r\n");
      out.write("						<h6>BÀI VIẾT MỚI NHẤT</h6>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/tai-tu-phuong-the-ngoc-qua-doi-o-tuoi-80-fd2-6215952-ngoisaovn-w1024-h670.jpg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://dantri.com.vn/giai-tri/tai-tu-phuong-the-ngoc-tran-tung-dung-qua-doi-vi-bao-benh-20211218072632278.htm\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Tài tử 'Phương Thế Ngọc'\r\n");
      out.write("										Trần Tùng Dũng qua...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Điện ảnh-Truyền hình</p>\r\n");
      out.write("								<p>Ngày 17/12, trang Sina đưa tin nam diễn viên Trần Tùng\r\n");
      out.write("									Dũng qua đời ở tuổi 80. Ông từng...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row m-1\">\r\n");
      out.write("							<div class=\"col-md-5 col-sm-7 col-5\">\r\n");
      out.write("								<img class=\"rounded img-fluid\" alt=\"\"\r\n");
      out.write("									src=\"img/song-gio-jack-120190716085030-1577267660211173990661-1628361005706629519382-16284086330031174000599.jpeg\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-7 col-sm-5 col-7\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"https://ictnews.vietnamnet.vn/game/truyen-hinh-trung-quoc-canh-bao-game-blockchain-lua-dao-400653.html\"\r\n");
      out.write("									class=\"\"> <span class=\"p-0\">Loạt drama chấn động\r\n");
      out.write("										showbiz Việt năm 2021...</span>\r\n");
      out.write("								</a> <br>\r\n");
      out.write("								<p class=\"genre p-1\">Âm nhạc</p>\r\n");
      out.write("								<p>2021 thực sự là một năm đầy biến động đối với CĐM và\r\n");
      out.write("									showbiz Việt. Từ ồn ào tình cảm...</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-md-4 col-sm-4 col-12 right mt-3 overlay\">\r\n");
      out.write("						<h6 class=\"title py-2\">TIN TỨC MỚI NHẤT</h6>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://baomoi.com/nhung-su-that-thu-vi-ve-doraemon-stand-by-me-2/c/41231145.epi\"\r\n");
      out.write("							class=\"nav-link\"> <span>Những sự thật thú vị về\r\n");
      out.write("								'Doraemon: Stand by Me 2'</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://baomoi.com/hai-tac-tro-lai-kang-ha-neul-han-hyo-joo-sieu-ngau-nhung-cai-bong-phan-dau-qua-lon/c/41230875.epi\"\r\n");
      out.write("							class=\"nav-link\"> <span>'Hải Tặc' trở lại: Kang Ha\r\n");
      out.write("								Neul - Han Hyo Joo siêu ngầu, nhưng 'cái bóng' phần đầu quá lớn</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://afamily.vn/truc-nhan-lan-ngoc-nhang-nhit-trong-hau-truong-mv-hit-tet-2022-day-roi-20211217145025331.chn\"\r\n");
      out.write("							class=\"nav-link\"> <span>Trúc Nhân, Lan Ngọc nhắng nhít\r\n");
      out.write("								trong hậu trường MV, hit Tết 2022 đây rồi?</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"https://game4v.com/huong-dan-cach-combo-ky-nang-free-fire-sau-khi-chrono-bi-nerf-825501.g4v\"\r\n");
      out.write("							class=\"nav-link\"> <span>Hướng dẫn cách combo kỹ năng\r\n");
      out.write("								Free Fire sau khi Chrono bị Nerf</span>\r\n");
      out.write("						</a> <img class=\"col-md-12 col-sm-12 col-12 right mt-3\" alt=\"\"\r\n");
      out.write("							src=\"img/4-1615133669050997629964.png\"> <img\r\n");
      out.write("							class=\"col-md-12 col-sm-12 col-12 right mt-3\" alt=\"\"\r\n");
      out.write("							src=\"img/anh-nen-bat-tay-hop-tac-kinh-doanh-toan-cau.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row mt-1 py-1 navbar navbar-expand-md\">\r\n");
      out.write("					<div class=\"logo col-md-2 col-sm-2 col-3\">\r\n");
      out.write("						<img class=\"navbar-brand\" height=\"40\"\r\n");
      out.write("							src=\"img/z3084541674816_e8384d2f3c44b472e9e4645a9b99f01e.jpg\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<form class=\"d-flex col-md-10 col-sm-10 col-9\" action=\"\">\r\n");
      out.write("						<div class=\"input-group search p-3\">\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Nhập nội dung cần tìm kiếm\">\r\n");
      out.write("							<div class=\"input-group-append\">\r\n");
      out.write("								<button class=\"btn btn-secondary\" type=\"button\">\r\n");
      out.write("									<i class=\"fa fa-search\"></i>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<section class=\"footer\">\r\n");
      out.write("				<!-- Footer -->\r\n");
      out.write("				<footer class=\" text-black text-center text-md-start\"\r\n");
      out.write("					style=\"background: rgba(4, 4, 4, 0.17);\">\r\n");
      out.write("					<!-- Grid container -->\r\n");
      out.write("					<div class=\"container p-4\">\r\n");
      out.write("						<!--Grid row-->\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("							<div class=\"col-lg-4 col-md-4 col-4 mb-4 mb-md-0\">\r\n");
      out.write("								<h5 class=\"text-uppercase\"\r\n");
      out.write("									style=\"color: #1A8C71; font-size: 13px\">Địa chỉ liên hệ</h5>\r\n");
      out.write("\r\n");
      out.write("								<p style=\"font-size: 13px;\">\r\n");
      out.write("									Đ/C:Hồ Tùng Mậu ,P.Mai Dịch,Q.Cầu Giấy ,Hà Nội <br> Điện\r\n");
      out.write("									thoại:+84 947 0938 347 <br> Email:Winchasersteam@gmail.com\r\n");
      out.write("									<br> Website: wwww.winchasers.com\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("							<div class=\"col-lg-4 col-md-4 col-4 mb-4 mb-md-0\">\r\n");
      out.write("								<h5 class=\"text-uppercase\"\r\n");
      out.write("									style=\"color: #1A8C71; font-size: 13px\">Liên hệ quảng cáo</h5>\r\n");
      out.write("\r\n");
      out.write("								<ul class=\" mb-4\" style=\"font-size: 13px;\">\r\n");
      out.write("									<li class=\"mb-2\"><a href=\"#!\" class=\"text-black\"\r\n");
      out.write("										style=\"text-decoration: none;\">Thông tin giới thiệu </a></li>\r\n");
      out.write("									<li class=\"mb-2\"><a href=\"#!\" class=\"text-black\"\r\n");
      out.write("										style=\"text-decoration: none;\"> Liên hệ gmail\r\n");
      out.write("											:windcharses@gmail.com</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("							<div class=\"col-lg-4 col-md-4 col-4 mb-2 mb-md-0\">\r\n");
      out.write("								<h5 class=\"text-uppercase mb-0\"\r\n");
      out.write("									style=\"color: #1A8C71; font-size: 0.9rem\">PAGE trên MXH</h5>\r\n");
      out.write("								<br>\r\n");
      out.write("\r\n");
      out.write("								<ul class=\"list-unstyled mb-2\">\r\n");
      out.write("									<li class=\"mb-2\"><a href=\"#!\" class=\"text-black\"\r\n");
      out.write("										style=\"text-decoration: none;\"> <i class=\"fab fa-facebook\"\r\n");
      out.write("											style=\"font-size: 13px;\"> https://m.facebook.com/</i>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"mb-2\"><a href=\"#!\" class=\"text-black\"\r\n");
      out.write("										style=\"text-decoration: none;\"> <i\r\n");
      out.write("											class=\"fab fa-google-plus\" style=\"font-size: 13px;\">\r\n");
      out.write("												https://mail.google.com/mail</i>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"mb-2\"><a href=\"#!\" class=\"text-black\"\r\n");
      out.write("										style=\"text-decoration: none; font-size: 13px\"> <img\r\n");
      out.write("											src=\"https://img.icons8.com/ios-filled/50/000000/zalo.png\"\r\n");
      out.write("											width=\"15px\">https://chat.zalo.me/\r\n");
      out.write("									</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--Grid column-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--Grid row-->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Copyright -->\r\n");
      out.write("					<div class=\"text-center p-3\"\r\n");
      out.write("						style=\"background-color: rgba(0, 0, 0, 0.2); font-size: 20px; font-weight: bolder; opacity: 0.6\">\r\n");
      out.write("						© Bản quyền thuộc về WindChasers | Cung cấp bởi figma</div>\r\n");
      out.write("					<!-- Copyright -->\r\n");
      out.write("				</footer>\r\n");
      out.write("				<!-- Footer -->\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
